export const CHAT_TIMEOUT_MS = 180000;
export const ID_MENSAJE_INICIO = 1;
export const ID_MENSAJE_REGISTRO = 0;
export const ID_MENSAJE_FIN_REGISTRO = 9;
export const ID_MENSAJE_TIMEOUT = 19;
export const ID_MENSAJE_ERROR_INTERNO = 20;
export const ID_MENSAJE_RESPUESTA_INVALIDA = 18;
export const ID_MENSAJE_CONEXION_CHAT = 0;
